MarshalX/yandex-music-api

yandex_music/status/account.py, yandex_music/track/track.py
- Birthday is now optional in account
- Fixed cover_uri str concatenation when cover_uri is None
=> Minor fixes and improvements

setup.py, yandex_music/download_info.py, yandex_music/utils/request.py
Фикс загрузки треков (https://github.com/MarshalX/yandex-music-api/issues/25).
Загрузка AAC временно недоступна.
=> Спасибо Яндекс, что пофиксили свой бэк. "randomTrash" RIP.

yandex_music/album/label.py
Привет! Сделал документацию на класс Label. #55
=> Добавил документацию на класс Label.

yandex_music/album/album.py, yandex_music/artist/artist.py, yandex_music/client.py, yandex_music/playlist/playlist.py, yandex_music/track/track.py
Остались коммиты с предыдущего PR из-за неправильного бранчинга
=> Добавил шорткаты лайк/дизлайк методов в track, artist, album, playlist

yandex_music/__init__.py, yandex_music/client.py, yandex_music/supplement/lyrics.py, yandex_music/supplement/supplement.py, yandex_music/supplement/video_supplement.py, yandex_music/track/track.py
- Добавлен класс `Supplement`
- Добавлен класс `VideoSupplement`
- Добавлен класс `Lyrics`
- Добавлен метод `get_supplement(self)` для класса `Track`
- Написана документация для новых классов
=> Добавил дополнительную информацию о треке (Текст, ссылки на видео)

yandex_music/album/album.py, yandex_music/artist/artist.py, yandex_music/client.py, yandex_music/download_info.py, yandex_music/landing/mix_link.py, yandex_music/playlist/playlist.py, yandex_music/playlist/user.py, yandex_music/status/account.py, yandex_music/track/track.py, yandex_music/track_short.py, yandex_music/tracks_list.py
=> Fix docstring shift

yandex_music/exceptions.py
=> Добавлена документация класса InvalidToken

yandex_music/exceptions.py
=> Добавлена документация класса Unauthorized

yandex_music/exceptions.py
=> Добавлена документация класса NetworkError

yandex_music/exceptions.py
=> Добавлена документация класса TimedOut

yandex_music/playlist/user.py
Пожалуйста обратите внимание на аттрибут verified, возможно я неправильно понял семантику.
=> Задокументировал класс User #53

yandex_music/search/search.py
=> Документация для Search

yandex_music/utils/request.py
=> Исправлен баг связанный с загрузкой файлов #149 найденный в #148

README.rst, yandex_music/client.py
Обработка каптчи при помощи сallback-функции
=> Callback-функция для обработки капчи

docs/source/yandex_music.playlist.playlist_absence.rst, docs/source/yandex_music.playlist.rst, tests/__init__.py, tests/conftest.py, tests/test_playlist.py, tests/test_playlist_absence.py, yandex_music/__init__.py, yandex_music/playlist/playlist.py, yandex_music/playlist/playlist_absence.py, yandex_music/utils/request.py, yandex_music/utils/response.py
=> Bugfix/issue #147

yandex_music/__init__.py, yandex_music/base.py, yandex_music/client.py, yandex_music/cover.py, yandex_music/download_info.py, yandex_music/exceptions.py, yandex_music/experiments.py, yandex_music/icon.py, yandex_music/invocation_info.py, yandex_music/pager.py, yandex_music/permission_alerts.py, yandex_music/promo_code_status.py, yandex_music/settings.py, yandex_music/track_short.py, yandex_music/tracks_list.py, yandex_music/video.py
Мердж в дев только для тестов на python 3.6
=> Тайп хинты

tests/conftest.py, tests/test_album.py, yandex_music/album/album.py
=> Добавлено опциональное поле version в класс Album.

yandex_music/client.py, yandex_music/track/track.py
=> Допиливание поддержи радио

yandex_music/search/search_result.py
Я только не совсем уверен, что свойство `order` - это номер страницы, т.к. я не понял как получить его не равным 0
=> Добавлена документация SearchResult

yandex_music/artist/link.py
=> Добавлена документация Link

.github/workflows/codecov.yml, .github/workflows/full_test.yml, .github/workflows/pypi.yml, .github/workflows/test.yml, tests/__init__.py, tests/conftest.py, tests/test_shot.py, tests/test_shot_data.py, tests/test_shot_event.py, tests/test_shot_type.py, yandex_music/__init__.py, yandex_music/client.py, yandex_music/shot/shot.py, yandex_music/shot/shot_data.py, yandex_music/shot/shot_event.py, yandex_music/shot/shot_type.py, yandex_music/utils/request.py
=> Плейлист с Алисой и поддержка её шотов

tests/test_tracks_similar.py, yandex_music/__init__.py, yandex_music/client.py, yandex_music/track/tracks_similar.py
=> Похожие треки

yandex_music/album/album.py
За что отвечают поля `original_release_year`, `buy`, `prerolls`, `regions`,  я так и понял, а так же возможно ошибся с `very_important`. Я нашел только [один альбом](https://music.yandex.ru/album/9647864) у которого `very_important == True` 
---
Закрывает #57
=> Добавлена документация Album

tests/conftest.py, tests/test_auto_renewable.py, yandex_music/account/auto_renewable.py
=> Поле product_id класса AutoRenewable теперь опционально 

yandex_music/feed/generated_playlist.py
=> Документация класса GeneratedPlaylist

yandex_music/artist/vinyl.py
=> Документация класса Vinyl

yandex_music/artist/ratings.py
=> Документация класса Ratings

yandex_music/artist/counts.py
=> Документация класса Counts

yandex_music/artist/description.py
=> Документация класса Description

yandex_music/search/suggestions.py
=> Документация класса Suggestions

yandex_music/genre/images.py
=> Документация класса Images

yandex_music/genre/title.py
=> Документация класса Title

yandex_music/genre/genre.py
=> Документация класса Genre

yandex_music/rotor/value.py
=> Документация класса Value

yandex_music/rotor/discrete_scale.py
=> Документация класса DiscreteScale

MANIFEST.in, docs/requirements-docs.txt, requirements-dev.txt, requirements.txt, setup.py
Добавлены ссылки проекта в setup.py
Добавлена команда для запуска тестов.
Тесты включены в пакет.
Список изменений добавлен в описание пакета на PyPi.
#215
=> Удалены requirements.txt файлы.

tests/conftest.py, tests/test_artist.py, yandex_music/artist/artist.py, yandex_music/artist/ratings.py
Поле week у класса Ratings теперь опциональное. #203
=> Исправлена десериализация несуществующего исполнителя.

yandex_music/rotor/ad_params.py
=> Документация класса AdParams

yandex_music/rotor/enum.py
=> Документация класса Enum

yandex_music/rotor/id.py
=> Документация класса Id

yandex_music/rotor/dashboard.py
=> Документация класса Dashboard

tests/test_rotor_settings.py, yandex_music/rotor/rotor_settings.py
=> Документация класса RotorSettings

tests/test_restrictions.py, yandex_music/rotor/restrictions.py, yandex_music/rotor/rotor_settings.py
=> Документация класса Restrictions

yandex_music/rotor/station.py
=> Документация класса Station

yandex_music/search/best.py
=> Документация класса Best

yandex_music/feed/track_with_ads.py
=> Документация класса TrackWithAds

yandex_music/playlist/playlist_id.py
=> Документация класса PlaylistId

yandex_music/playlist/case_forms.py
=> Документация класса CaseForms

yandex_music/playlist/case_forms.py, yandex_music/playlist/made_for.py
=> Документация класса MadeFor

tests/conftest.py, tests/test_search.py, tests/test_search_result.py, yandex_music/search/search_result.py
для определения типа результата поиска по объекту #229
=> Добавлено поле type для класса SearchResult

yandex_music/track/normalization.py
=> Документация класса Normalization

tests/conftest.py, tests/test_track.py, yandex_music/track/track.py
=> В класс Track добавлены ранее неизвестные поля: version, remember_position

yandex_music/playlist/playlist.py
=> Добавлена документация для класса Playlist

yandex_music/landing/track_short_old.py
=> Документация класса TrackShortOld

yandex_music/feed/day.py
=> Документация класса Day

yandex_music/feed/feed.py
=> Документация класса Feed

yandex_music/feed/event.py
=> Документация класса Event

yandex_music/feed/artist_event.py
=> Документация класса ArtistEvent

yandex_music/feed/album_event.py
=> Документация класса AlbumEvent

yandex_music/landing/track_id.py
=> Документация класса TrackId

yandex_music/landing/mix_link.py
=> Документация класса MixLink

yandex_music/artist/brief_info.py
=> Документация класса BriefInfo

yandex_music/exceptions.py
=> Документация класса BadRequest

yandex_music/landing/landing.py
=> Документация класса Landing

yandex_music/album/track_position.py
=> Документация класса TrackPosition

yandex_music/rotor/sequence.py
=> Документация класса Sequence

yandex_music/track/major.py
=> Документация класса Major

yandex_music/rotor/dashboard.py, yandex_music/rotor/station_tracks_result.py
=> Документация класса StationTracksResult

yandex_music/rotor/station_result.py
=> Документация класса StationResult

yandex_music/landing/chart_item.py
=> Документация класса ChartItem

yandex_music/landing/chart.py
=> Документация класса Chart

yandex_music/artist/artist.py
Документация к классу Artist
close #91
=> Документация к классу Artist

yandex_music/landing/block.py
=> Документация класса Block

yandex_music/landing/block_entity.py
=> Документация класса BlockEntity

yandex_music/landing/personal_playlists_data.py
=> Документация класса PersonalPlaylistsData

yandex_music/landing/play_contexts_data.py
=> Документация класса PlayContextsData

yandex_music/landing/play_context.py, yandex_music/landing/play_contexts_data.py
=> Документация класса PlayContext

yandex_music/landing/promotion.py
=> Документация класса Promotion

yandex_music/utils/response.py
=> Документация класса Response

yandex_music/utils/difference.py
=> Документация класса Operation

docs/source/yandex_music.utils.difference.rst, yandex_music/utils/difference.py
=> Документация класса Difference

docs/source/yandex_music.utils.request.rst, yandex_music/utils/request.py
=> Документация класса Request

yandex_music/artist/artist.py, yandex_music/track/track.py, yandex_music/track_short.py
Документация к классу Track
close #103
=> Документация к классу Track

docs/source/yandex_music.base.rst, docs/source/yandex_music.exceptions.rst, docs/source/yandex_music.rst, yandex_music/base.py
=> Документация класса YandexMusicObject

tests/conftest.py, tests/test_description.py, yandex_music/artist/description.py
=> Исправлено название поля с ссылкой на источник в классе Description

MANIFEST.in, setup.py
https://packaging.python.org/guides/making-a-pypi-friendly-readme/
=> Исправлена установка с pypi. Просто Making a PyPI-friendly README

tests/__init__.py, tests/conftest.py, tests/test_album.py, tests/test_artist.py, tests/test_brief_info.py, tests/test_cover.py, tests/test_product.py, tests/test_renewable_remainder.py, tests/test_status.py, tests/test_subscription.py, tests/test_track.py, tests/test_vinyl.py, yandex_music/__init__.py, yandex_music/account/product.py, yandex_music/account/renewable_remainder.py, yandex_music/account/status.py, yandex_music/account/subscription.py, yandex_music/album/album.py, yandex_music/artist/artist.py, yandex_music/artist/brief_info.py, yandex_music/artist/vinyl.py, yandex_music/cover.py, yandex_music/track/track.py
=> Новые поля собранные за 3 недели

yandex_music/client.py
=> Добавлен второй вариант отправки запроса на получение плейлиста в users_playlists метод

docs/source/yandex_music.playlist.rst, docs/source/yandex_music.playlist.tag.rst, docs/source/yandex_music.playlist.tag_result.rst, tests/__init__.py, tests/conftest.py, tests/test_tag.py, tests/test_tag_result.py, yandex_music/__init__.py, yandex_music/client.py, yandex_music/playlist/tag.py, yandex_music/playlist/tag_result.py
Метод tags() у Client.
Новые классы: TagResult, Tag.
Close #192
=> Добавлено получение тегов.

yandex_music/client.py
Изменения:
- Добавлен метод `Client.playlists_collective_join` + псевдоним
---
close #317
=> Присоеденение к коллективному плейлисту (#317)

yandex_music/landing/landing.py
=> Исправлен тип у поля landing.blocks

yandex_music/icon.py
Не всегда нужно сохранять файл.
Иногда нужно просто получить путь что бы отдать его дальше.
=> Добавлен метод получения аддреса иконки

yandex_music/tracks_list.py
Я правильно понимаю, что имелось в виду `TracksList`, а не `Track`?
close #380
=> Добавлен __len__ для TracksList

README.rst
=> Фикс README.rst (#381)

yandex_music/client.py
=> Fix тайпхинта

examples/player.py
использует VLC по умолчанию, но можно поменять через аргументы
=> Примеры: плеер плейлистов

tests/conftest.py, tests/test_album.py, tests/test_deactivation.py, tests/test_playlist.py, tests/test_supplement.py, tests/test_video_supplement.py, yandex_music/account/deactivation.py, yandex_music/album/album.py, yandex_music/playlist/playlist.py, yandex_music/supplement/supplement.py, yandex_music/supplement/video_supplement.py, yandex_music/track/track.py
=> Новые поля + фиксы старых

yandex_music/album/album.py, yandex_music/landing/mix_link.py, yandex_music/landing/promotion.py, yandex_music/landing/track_id.py, yandex_music/playlist/playlist.py, yandex_music/playlist/playlist_id.py, yandex_music/queue/queue.py, yandex_music/queue/queue_item.py, yandex_music/search/search.py, yandex_music/track/track.py, yandex_music/track_short.py, yandex_music/tracks_list.py
=> Сокращения

generate_camel_case_aliases.py
=> Генератор camel case псевдонимов методам классов

generate_async_version.py, yandex_music/client.py, yandex_music/client_async.py, yandex_music/utils/request.py, yandex_music/utils/request_async.py
=> Добавлена возможность задать глобальный timeout для всех запросов

yandex_music/client.py, yandex_music/client_async.py, yandex_music/download_info.py, yandex_music/exceptions.py, yandex_music/experiments.py, yandex_music/pager.py
=> Исправлены опечатки в документации

yandex_music/client.py, yandex_music/client_async.py, yandex_music/exceptions.py, yandex_music/playlist/case_forms.py, yandex_music/playlist/tag.py, yandex_music/playlist/tag_result.py, yandex_music/utils/difference.py
=> добавил ссылки на задачи к TODO не связанных с документацией

generate_async_version.py, generate_camel_case_aliases.py
Добавил скриптам для генерации права на исполнение и шебанг
=> chmod +x generate_async_version.py и generate_camel_case_aliases.py

docs/source/yandex_music.track.lyrics_major.rst, docs/source/yandex_music.track.rst, docs/source/yandex_music.track.track_lyrics.rst, docs/source/yandex_music.utils.convert_track_id.rst, docs/source/yandex_music.utils.rst, docs/source/yandex_music.utils.sign_request.rst, examples/lyrics_playing_track.py, tests/__init__.py, tests/conftest.py, tests/test_convert_track_id.py, tests/test_lyrics_major.py, tests/test_sign_request.py, tests/test_track_lyrics.py, yandex_music/__init__.py, yandex_music/client.py, yandex_music/client_async.py, yandex_music/supplement/lyrics.py, yandex_music/supplement/supplement.py, yandex_music/track/lyrics_major.py, yandex_music/track/track.py, yandex_music/track/track_lyrics.py, yandex_music/utils/convert_track_id.py, yandex_music/utils/sign_request.py
=> Добавление нового эндпоинта для получения текста

yandex_music/utils/request.py, yandex_music/utils/request_async.py
=> Заголовок из новой версии

yandex_music/track/track_lyrics.py
=> Исправлен метод fetch_lyrics_async

yandex_music/utils/request.py, yandex_music/utils/request_async.py
=> Обновлен HTTP заголовок

yandex_music/search/search.py
Изменен несуществующий атрибут type_ на type
=> Исправлен get_page и get_page_async в классе Search

yandex_music/landing/landing_list.py
Мы получаем PlaylistId, а не int
=> Исправление тайпхинта в классе LandingList

yandex_music/like.py
=> Исправлен метод `de_list` для класса `List`
